### ISSUE TITLE
harfmode: confusing script handling

### ISSUE THREAD

**Issue by u-fischer** [latex3/luaotfload#117]
otfinfo reports for the font `NotoSerifMyanmar-Regular.ttf` that it contains only the mym2 script:

~~~~
$ otfinfo -s NotoSerifMyanmar-Regular.ttf
mym2            <unknown script>
mym2.KSW        <unknown script>/<unknown language>
mym2.MON        <unknown script>/Mon

~~~~

So fontspec quite correctly reports for the following document that the Myanmar2/mymr script is not in the font, but with xelatex one gets nevertheless in all cases the correct output (according to https://tex.stackexchange.com/questions/431430/burmese-and-lualatex):

![image](https://user-images.githubusercontent.com/4047173/68396688-3b3d6400-0172-11ea-8aa7-c5221ff5b791.png)

With luahblatex one gets the correct output only with the unknown script `mymr`, and also only without the fontspec interface as fontspec removes the unknown script:

![image](https://user-images.githubusercontent.com/4047173/68396878-8f484880-0172-11ea-8fd9-675be9697e08.png)

~~~~~
\documentclass{article}
\usepackage{iftex}
\usepackage{fontspec}
\newfontscript{Myanmar2}{mymr}

\newfontfamily{\burmeseFamilymymII}{NotoSerifMyanmar-Regular.ttf}[Renderer=Harfbuzz,Script=Myanmar]

\newfontfamily{\burmeseFamilymymr}{NotoSerifMyanmar-Regular.ttf}[Renderer=Harfbuzz,Script=Myanmar2] 

\newfontfamily{\burmeseFamilynoscript}{NotoSerifMyanmar-Regular.ttf}
\ifluatex
\font\burmesefontmymII={file:NotoSerifMyanmar-Regular.ttf:mode=harf;script=mym2;}

\font\burmesefontmymr={file:NotoSerifMyanmar-Regular.ttf:mode=harf;script=mymr;}

\font\burmesefontnoscript={file:NotoSerifMyanmar-Regular.ttf:mode=harf;}
\fi

\begin{document}
{\burmeseFamilymymII င်းကွန်းင်းလောင်းတော်ကြီး} fontspec + mym2

{\burmeseFamilymymr င်းကွန်းင်းလောင်းတော်ကြီး} fontspec + mymr

{\burmeseFamilynoscript င်းကွန်းင်းလောင်းတော်ကြီး} fontspec + noscript

\ifluatex
{\burmesefontmymII င်းကွန်းင်းလောင်းတော်ကြီး } mym2

{\burmesefontmymr င်းကွန်းင်းလောင်းတော်ကြီး} mymr 

{\burmesefontnoscript င်းကွန်းင်းလောင်းတော်ကြီး} no script
\fi
\end{document}
~~~~~

**Comment by khaledhosny** [comment]
The scripts passed to harf mode should be ISO 15924 script tags (see [`hb_script_from_string()`](https://harfbuzz.github.io/harfbuzz-hb-common.html#hb-script-from-string) documentation), and HarfBuzz will select the appropriate OpenbType script tag (preferring verion 2 tags if the font supports both).

To force selecting an exact OpenType tag, private ISO tags are supported in the form `x-hbscXXXX` where `XXXX` is the desired OpenType script tag.

The same for language tags (using x-hbotXXXX`, and both can be combined).

Otherwise if compatibiklity with XeTeX/fontloader is desired, the code should be modified to ue raw luaharfbuzz `Tag` instead of `Script` and `Language`.

**Comment by khaledhosny** [comment]
(I have to stress again that, all of this would have been unnecessary if my original code that detected script from the Unicode character properties would have been kept, instead of artificially handicapping it to match the limitations of XeTeX/fontloader).

**Comment by khaledhosny** [comment]
(Not sure of `Tag` will actually work, we need to the equivalent of `hb_ot_tag_to_script` from luaharfbuzz).

**Comment by zauguin** [comment]
> (Not sure if `Tag` will actually work, we need to the equivalent of `hb_ot_tag_to_script` from luaharfbuzz).

While `hb_ot_tag_to_script` would solve the problem of not allowing `mym2`, getting actual compatible behavior would need `hb_ot_tags_to_script_and_language` AFAICT.

**Comment by zauguin** [comment]
> (I have to stress again that, all of this would have been unnecessary if my original code that detected script from the Unicode character properties would have been kept, instead of artificially handicapping it to match the limitations of XeTeX/fontloader).

You probably are not surprised that I  disagree here, but I think this is actually a use case where forcing an automatically determined script isn't always the right thing: If I have e.g. a font with `mymr` and `mym2` support, I should have the option to force `mymr`.

**Comment by khaledhosny** [comment]
Apart from testing purposes, no you probably won’t (`mymr` does not exist any way, but for other Indic scripts that has version 2 tags, these were introduced because the version one model proved to be insufficient, and fonts having both tags want version 2 to be used whenever it is supported and version one is a fallback for legacy applications.), which is evident by the fact that most higher level applications don’t have a way to manually select text script at all.

**Comment by u-fischer** [comment]
okay this explains why mymr work (or should it better be Mymr? The list shows all code names with uppercases). 

But I'm right that the fontloader would need the name of the correct script so mym2 in my example?

That would mean be that either fontspec will have to learn to handle harf/xetex and fontloader differently or the harf mode learns to handle the "wrong" script input and translates a version 2 tag to the ISO-script name or passes it correctly forward.

@zauguin any preference here?

BTW: Does the current harf code do anything with the language tag, (KSW and MON in my example)?

**Comment by zauguin** [comment]
> But I'm right that the fontloader would need the name of the correct script so mym2 in my example?

Yes.

> 
> That would mean be that either fontspec will have to learn to handle harf/xetex and fontloader differently or the harf mode learns to handle the "wrong" script input and translates a version 2 tag to the ISO-script name or passes it correctly forward.
> 
> @zauguin any preference here?

As I said I strongly believe that users should be able to force any script handling they want, especially since fontspec already makes sure that e.g. newer versions are preferred. While this shouldn't be necessary for well-behaved fonts, I don't believe that fonts in general are well behaved and luaotfload should support all use-cases. So IMO the tag should be passed forward, either by using `hb_ot_tags_to_script_and_language` or by doing an equivalent operation in Lua. So to ensure that we can test properly and don't have to wait for a new engine version, I think we should remap in the `harf` code for now.

> 
> BTW: Does the current harf code do anything with the language tag, (KSW and MON in my example)?

It is passed to HarfBuzz after casing normalization, there it should affect the available features (if the used font does differentiate based on language).

**Comment by u-fischer** [comment]
> As I said I strongly believe that users should be able to force any script handling they want,

Yes, even if it is only useful for testing or to show on a slide how a bad implementation looks like. It is one of the characteristik of LaTeX that you have more control and options. 

> I think we should remap in the harf code for now.

Yes, `script=mym2` or `Script=Myanmar` should work as mym2 is in the font.  

The question is if `script=mymr` and `Script=Myanmar2` should work too? For fontspec that would mean that either it must adapt its script test so that if a font has mym2 it means "mymr is allowed too", or luaotfload must lie to fontspec in harf mode and claim that mymr is in the font too. Or should we add a new key isotag to avoid the confusion?

**Comment by u-fischer** [comment]
@zauguin  for the myanmar for it now works fine. But in the scripts-demo file (in the doc folder), the deva and the banglafont now fails, while the tibetan works fine. The difference I see here is that the failing fonts have both scripts (deva/dev2 and beng/ben2). Could this confuse the code?

~~~~
\documentclass{article}
\font\devafontA={file:NotoSansDevanagari-Regular.ttf:mode=harf;script=dev2;}
\font\devafontB={file:NotoSansDevanagari-Regular.ttf:mode=harf;script=deva;}

\begin{document}
{\devafontA क्रर्कि }

{\devafontB क्रर्कि }
\end{document}
~~~~

**Comment by u-fischer** [comment]
Works ok in version 3.11
