### ISSUE TITLE
--prefer-texmf at tex level?

### ISSUE THREAD

**Issue by kberry** [latex3/luaotfload#130]
Is it possible to somehow specify the equivalent of --prefer-texmf at the TeX level? I would find it quite helpful. I just lost an hour debugging why an old version of a TL font was being found; the answer was old (other debugging) entries in my ~/.fonts.conf. 

The reason I ask here and not in fontspec is that my TeX file already had
\setmonofont[Scale = .95]{zcoN-Regular.otf}
so it is already asking for filename lookups. I was quite surprised to learn that my .fonts.conf was relevant in any way with that specification. I realize maybe the change still needs to be in fontspec, but thought I'd start here.

Thanks.

**Comment by zauguin** [comment]
We are not really providing any TeX level interfaces, but it is possible to set this using Lua code:

`--prefer-texmf` can be activated using

```
\directlua{
  fonts.names.set_location_precedence { "local", "texmf", "system" }
}
```

fontspec could also explicitly request to only lookup a filename using kpathsea by using `\font\xxx "kpse:zcoN-Regular.otf"` instead of `\font\xxx "[zcoN-Regular.otf]"` but that interface isn't supported by fontspec as far as I can tell.

**Comment by kberry** [comment]
Thanks Marcel. I will suggest it to Will.
