### ISSUE TITLE
debugging output: unnecessary ellipses and utf-8 and v's

### ISSUE THREAD

**Issue by kberry** [latex3/luaotfload#131]
the luaotfload-tool -vvvvvvvvv output includes lines like this:
luaotfload | db : Loading font ../opentype/google/noto/NotoSerif-ExtraBold.otf

I don't see the purpose of truncating the path just so the line ends up being 79 characters. The full path may be exactly what is interesting; it was for me. Anyway, this is the debugging output, so no need to worry about terminal widths. There are plenty of other longer lines.

also, in this line:
luaotfload | db : Path â\200\234.â\200\235 matches $PWD (â\200\234/home/...
I suggest/request using the simple ASCII ' character instead of UTF-8 quotes (at least I assume that's what they are). Nothing is gained by Unicode quotes in debugging output that I can see, whereas sticking to ASCII simplifies so much ...

oh, and one other thing do you really have/need so many independent debugging levels? typing/copying so many v's is error-prone.

thanks.

**Comment by zauguin** [comment]
> the luaotfload-tool -vvvvvvvvv output includes lines like this:
> luaotfload | db : Loading font ../opentype/google/noto/NotoSerif-ExtraBold.otf
> 
> I don't see the purpose of truncating the path just so the line ends up being 79 characters. The full path may be exactly what is interesting; it was for me. Anyway, this is the debugging output, so no need to worry about terminal widths. There are plenty of other longer lines.

This is only done for some special lines of log output, where a lot of lines are generated which are not very useful in most cases. For these, the last log line is overwritten with the next one for most logging levels to avoid excessive output. This only works if the last line wasn't longer than the terminal width, so we go to some extra lengths to ensure this.
All these lines are also written to the log without truncation, so if you make the log visible (e.g. by passing `--log=stdout` to `luaotfload-tool`) you get the full paths. 

> 
> also, in this line:
> luaotfload | db : Path â\200\234.â\200\235 matches $PWD (â\200\234/home/...
> I suggest/request using the simple ASCII ' character instead of UTF-8 quotes (at least I assume that's what they are). Nothing is gained by Unicode quotes in debugging output that I can see, whereas sticking to ASCII simplifies so much ...

One thing we gain here is exactly what you observed: If someone posts debugging output, we see how their terminal handles Unicode characters. That can be relevant if other Log output coontains more relevant Unicode entries, e.g. because someone got creative while naming their font files.

It does look a bit odd though, so I would be OK with changing it. @u-fischer What do you think?

> 
> oh, and one other thing do you really have/need so many independent debugging levels? typing/copying so many v's is error-prone.

If you want to avoid writing `-vvvvvvvvv`, you can use `--verbose` with a number: e.g. `--verbose=9` That's not really shorter, but it is more clear and less error-prone.

**Comment by u-fischer** [comment]
> It does look a bit odd though, so I would be OK with changing it. @u-fischer What do you think?

I can't see utf8 quotes (or I didn't understand how Karl got it) but I don't mind to remove them.

**Comment by zauguin** [comment]
The remaining question is what to use as the new value. We can either print paths as `"%s"` or as `%q`. Both use ASCII quotes, but the %q option would escape all special characters as Lua strings. So e.g. `\` becomes `\\`. Normally I think this is better to ensure that there can not be any confusion due to unprintable characters, but it might be confusing for Windows users where `\` is quite a common path separator.

So I think you are more suited to decide if that would be too confusing.

**Comment by kberry** [comment]
I'm not sure if you intended this for me or Ulrike. I don't feel any special attachment to either way, but my preference would be for the first, "%s". Simplicity. (My hope is that unprintable characters would show up as their numeric values, one way or another.)

**Comment by zauguin** [comment]
@kberry I mostly intended this for @u-fischer (mostly because she is a Windows user) but

>  (My hope is that unprintable characters would show up as their numeric values, one way or another.)

That is the reason why I prefer `%q`. On all terminals I know, unprintable characters are, well, unprintable and are either shown as useless replacement characters, space, nothing, or similar.

**Comment by kberry** [comment]
I have no quarrel with %q. But, in either case, my main concern is with the log file. What is displayed on the terminal can't be expected to be a perfect representation of reality, for exactly the reasons you mention ...

**Comment by zauguin** [comment]
We use regular quotes with %q now in dev.
