### ISSUE TITLE
wrong \tagcode reported

### ISSUE THREAD

**Issue by schlcht** [latex3/luaotfload#146]
If `luaotfload` is loaded, luatex will  report all `\tagcode`s as zero, even for legacy fonts: 

```
\font\x=cmr12
\x
fi \the\tagcode\x`\f 

\input luaotfload.sty
\font\x=cmr12
%\font\x=[lmroman12-regular.otf]:script=latn;+trep;+tlig;%mode=base; 
\x
fi \the\tagcode\x`\f 

\tagcode\x`\f=-1 
fi \the\tagcode\x`\f
\bye
```

Curiously, setting the tagcode to -1 (in order to suppress ligatures), still works.

**Comment by zauguin** [comment]
> If `luaotfload` is loaded, luatex will report all `\tagcode`s as zero, even for legacy fonts:

Technically not all tagcodes are zero, only the tagcodes which would otherwise be 1...

This is not something luaotfload can change. (LuaTeX only ever sets the tagcode to `1` when parsing TFM files and not going through Lua, so there is no way of having a tagcode `1` without undefining the `define_font` callback (or changing LuaTeX of course).

> Curiously, setting the tagcode to -1 (in order to suppress ligatures), still works.

This might appear surprising given that LuaTeX doesn't use the tagcode here, but for compatibility LuaTeX just removes all kerning/ligaturing rules for this character if you try to set the tagcode to -1.
