### ISSUE TITLE
Kerning works in math mode but not in display math mode

### ISSUE THREAD

**Issue by cao-** [latex3/luaotfload#174]
```
\fontfam[garamond]

\directlua
  {fonts.handlers.otf.addfeature 
    {
    name = "kerncorr",
    type = "kern",
    data = {
    ["("] = { ["𝑓"] = 80, ["𝑔"] = 50 },
    }
  }
}
\_def\_normalmath{%
    \_loadumathfamily 1 {[Garamond-Math]}{+kerncorr} % Base font
    \_loadmathfamily  4 rsfs              % script
    \_setunimathdimens
}%
\normalmath % we must reload Math font collection with {+kerncorr} again.

Test: $(f+g)$.

$$(f+g)$$

\bye
```

This code is in the OpTeX format.  I'm sorry but I don't know how to convert it to plain luatex nor to LaTeX.  Anyhow, it should be understandable, I hope.  As you can see, I added as font feature a kerning in between the opeing parenthesis and the italic letter f (and also g).  Then I tried to print `(f` both in text math mode and display math mode. As you can see [here](https://ibb.co/RPRKLr6), the kerning doesn't appear in display mode.

For more information refer to the originating question on [TeXStackExchange](https://tex.stackexchange.com/questions/580645/automatically-add-space-after-parenthesis-in-math-mode-if-followed-by-certain-ch/580676?noredirect=1#comment1460844_580676)

**Comment by zauguin** [comment]
TeX does apply kerning and ligatures in mathmode only after "Ord atoms" (there are some additional conditions, see the TeXbook, Appendix G, step 14 for details). LuaTeX is mostly compatible with this, therefore your kerning isn't applied since `(` is a "Open atom", not a "Ord atom".

Of course this means that the kerning shouldn't be inserted in inline math either. This is a sideeffect because the text ends up directly in the bigger hlist of the paragraph and in LuaTeX kerning is applied for the whole hlist, so in some cases (when the pair is not in any group and no spacing is inserted between them according to the math algorithm) the regular kerning pass accidentially inserts kerns in mathmode too. We could work around this, but since it only has an effect if the font has an odd kern/ligature which should never be used it doesn't seem to be worth the overhead.

In any case it's an engine property unrelated to luaotfload.

**Comment by olsak** [comment]
OK, it is not related to luaotfload. But I add a notice here about concept of luaTeX engine behavior. Knuth didn't implement the auto-kerning between Open Ord because he didn't suppose that they are from the same font. It was common in these days: open `(` was from family 0 and Ord was typically from family 1. But today, all math symbols can be typeset from single font. The kerning between object where isn't inserted \thinmuskip (or similar) should be auto-kerned. Note that there is an asymmetry in Knuth's concept: Ord-Close pair is kerned but Open-Ord not.
