### ISSUE TITLE
Wrong processing of CharacterVariant for font Iosevka (working in xelatex)

### ISSUE THREAD

**Issue by Rmano** [latex3/luaotfload#202]
Install the font Iosevka; this is a direct link to the version I tested with: https://github.com/be5invis/Iosevka/releases/download/v10.1.1/super-ttc-iosevka-10.1.1.zip

and the MWE: 

```latex
\documentclass[12pt]{article}
\usepackage{fontspec}
\setmonofont{Iosevka}[CharacterVariant={36:2, 26:6, 71:4}]
%
\begin{document}
\ttfamily
text in mono font 0123 4567 89 arrow: <- and shapes of AaAa; more words to add ``i'' (so few ies here\dots ¡and no k!)
\end{document}
```

Running with a current `xelatex` (`This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021) (preloaded format=xelatex)`) the result is the expected one (the "a" shape is a single-storey one):

![image](https://user-images.githubusercontent.com/6414907/132687586-50a74560-c169-44fa-a6a8-bbfbdce0a2a1.png)

with `lualatex` (`This is LuaHBTeX, Version 1.13.2 (TeX Live 2021) `) I have:

![image](https://user-images.githubusercontent.com/6414907/132687797-36d6bb3f-8bd8-4664-99f2-24d198c84261.png)

I am not sure if it's user error, a font problem or a luaotfload error...

Removing the `CharacterVariant` switch gives a correct result.

**Comment by zauguin** [comment]
See Hans' answer on the ConTeXt list for some context on this: There is an intentional feature of the fontloader which uses the number as a factor to repeat the last character in a ligature and because of how the font is organized this also triggers here for the dot of the `i`. Anyway the latest fontloader no longer does this by default, so this is fixed in `dev`.

**Comment by Rmano** [comment]
@zauguin nice to know! Thank you for writing this here (I am not on the ConTeXt list...).
Closing it (correct?)!
