### ISSUE TITLE
Harfbuzz renderer + OTF: extracted text contain spurious space between characters

### ISSUE THREAD

**Issue by rajeeshknambiar** [latex3/luaotfload#210]
Hello,

LuaHBTeX allows to properly copy/extract complex script text/content from generated PDF.

I have observed a curious issue that is present only in the `OTF` version of a font, RIT Rachana (`TTF` format of the same version works fine). Both formats of the font are available at [1].
The issue is that the text extracted from PDF when `OTF` font used contains spurious spaces (but PDF output is correct with either font formats).

Steps to reproduce the issue:
1. MWE
```latex
\documentclass{article}
\usepackage{fontspec}
\usepackage{polyglossia}
\setdefaultlanguage{malayalam}
\setotherlanguages{english}

% Using OTF causes spurious space between characters in extracted text
% Adjust 'Path' if necessary
\newfontfamily\malayalamfont[Script=Malayalam,Path=fonts/otf/]
{RIT-Rachana-Regular.otf}[Renderer=Harfbuzz]
% TTF version
% \newfontfamily\malayalamfont[Script=Malayalam,Path=fonts/ttf/]%
%{RIT-Rachana-Regular.ttf}[Renderer=Harfbuzz]

\begin{document}
\noindent
ദൈവമേ! കാത്തുകൊൾകങ്ങു\\
കൈവിടാതിങ്ങു ഞങ്ങളെ;
\end{document}
```
2. Compile this file (unzipping/placing the font file also at `fonts/otf` and `fonts/ttf` directories) using `lualatex-dev` (I am using `LuaHBTeX, Version 1.13.0 (TeX Live 2021)`)
3. Either copy the text using a PDF viewer, or extract text using `pdftotext -nopgbrk output.pdf output.txt`
4. Observe that copied/extract content have unnecessary/spurious spaces between characters (wrong outcome), e.g. 
```
ദൈ വ മേ ! ക ാ ത്തു
 ക ൊ ൾ ക ങ്ങു
 ```
5. Repeat steps 2 & 3 by using `TTF` format of the font instead and observe that copied content do not contain unnecessary spaces (correct outcome), e.g. `ദൈവമേ! കാത്തുകൊൾകങ്ങു`.

Please let me know if I can provide any further information to troubleshoot the issue.

[1]  RIT Rachana fonts: https://gitlab.com/rit-fonts/RIT-Rachana/-/jobs/artifacts/1.3/download?job=build-tag

**Comment by zauguin** [comment]
Not much we can do here. Spaces in PDF are not explicitly encoded by inferred by the PDF viewer based on viewer specific heuristic about the glyph positions. Once LaTeX produces fully tagged documents this problem should disappear with sufficiently compliant viewers, but I'm not aware of many other tricks here.

This leads to much worse outcomes for the OTF version than the TTF version since the OTF version has a untypical `unit per em` value which triggers a trick in LuaTeX to fix rendering on viewers which can't deal with such fonts, but this system can't really be influenced without engine changes either (AFAICT).

**Comment by khaledhosny** [comment]
I think space can be represented in PDF like any other glyph, but PDFTeX (and by extension LuaTeX) does not do this. I’m not sure if doing this will stop the heuristic in PDF readers or not. I’m not sure if it can be done at luaotfload level either (replacing glue nodes that come from space by glyph nodes after line breaking? Probably not that simple).

**Comment by zauguin** [comment]
They can be represented and this can be used to improve the heuristics by adding spaces, but in my experience this does not stop most viewers from adding spaces they would have added anyway. It is related to the note about tagged documents though: Fully tagged documents *must* use explicit space glyphs and for such documents viewers are also expected to respect this.

Regarding support for this in pdfTeX/LuaTeX: In pdfTeX there is a primitive to add explicit space glyphs, while in LuaTeX this can be implemented in Lua code.

> I’m not sure if it can be done at luaotfload level either (replacing glue nodes that come from space by glyph nodes after line breaking? Probably not that simple).

It can, but since it's already implemented in `tagpdf` and mostly relevant for tagged documents there's no need to duplicate it here.

**Comment by rajeeshknambiar** [comment]
> This leads to much worse outcomes for the OTF version than the TTF version since the OTF version has a untypical `unit per em` value which triggers a trick in LuaTeX to fix rendering on viewers which can't deal with such fonts

Thanks for this information, so it really is a problem with OTF files in general. For the time being, I will resort to TTF files which work fine for our use case.

**Comment by u-fischer** [comment]
if I only activate the interwordspace code from tagpdf there is no improvement. If I fully tag by using (in a current lualatex-dev) `\DocumentMetadata{testphase=phase-II}` before documentclass copy&paste from adobe gives this:

~~~~
ദൈ
വ
!
􀀄കാത്തു കാൾകങ്ങു
􀄗 ക വിടാതിങ്ങു􀀄ഞങ്ങളെ ;
~~~~

the results with other viewers are worse.

**Comment by zauguin** [comment]
@u-fischer Looking at the PDF file it seems that the tagging and the /ActualText markers interfere rather badly. This should probably be considered a new issue.

**Comment by u-fischer** [comment]
@zauguin yes, I think I saw already once in another connection that they can clash.  I added a reminder at tagpdf, we will have to check how we can coordinate the code.
