### ISSUE TITLE
Greek script: distinction between tonos and oxia

### ISSUE THREAD

**Issue by ralessi** [latex3/luaotfload#216]
Something is wrong with the default Node renderer for all Greek “oxiai”, which is the same sign as our acute accent, are replaced with “tonoi”, which are small vertical strokes above the vowels.  See for example the following mwe:

```latex
\documentclass{article}

\usepackage{fontspec}
\setmainfont{Old Standard}

\begin{document}

This is an oxia: ´

This is a tonos: ΄

\textbf{Default renderer:}

Oxia:
οὐδέν τί μοι δοκέει (wrong: input has oxiai, not tonoi)

Tonos:
οὐδέν τί μοί δοκέει (right: input has tonoi)


\addfontfeature{Renderer=Harfbuzz}
\textbf{Harfbuzz renderer:}

Oxia:
οὐδέν τί μοι δοκέει (right: input has oxiai)

Tonos:
οὐδέν τί μοί δοκέει (right: input has tonoi)

\end{document}
```

And check out the PDF output:
![2022-03-07_12-02](https://user-images.githubusercontent.com/389498/157019587-67702969-109d-4ee2-a8b0-80189a820392.png)

As can be seen, unlike the default renderer, Harfbuzz prints the Greek as expected.

PS: To verify this, please use the [development version of OldStandard-Regular.otf, here](https://gitlab.com/ralessi/oldstandard/-/archive/master/oldstandard-master.zip?path=otf/testing).

**Comment by zauguin** [comment]
This can be resolved for an individual document by using `\setmainfont[RawFeature=-normalize]{Old Standard}`.

The problem is that new luaotfoad versions normalize to NFC before shaping and Unicode considers the composed characters with tonos and with oxia to be the same, therefore they get normalized to the same glyph. I'm not sure what to do about that.

Some options:

  * Disable normalization by default when `script=grek` is set. But this can reintroduce other issues and preserves the distinct rendering of equivalent input, leading e.g. to issues like https://tex.stackexchange.com/q/542789/80496 when the editor doesn't play the same game.
  * Automatically add the equivalent of https://tex.stackexchange.com/q/542789/80496 whenever the language is set to polytonic greek. This solves the issue with Oxia/Tonos as long as the language is set correctly independent from the input, but it doesn't work if the language isn't set (which might happen due to fontspec removing it to an an unsupported language)
  * Consider this a font bug since canonically equivalent characters should look the same. We would have a point, but declaring it someone else's problem is not exactly the most productive solution...

@jbezos Any opinion on this?

**Comment by ralessi** [comment]
Thank you for your very detailed answer.

> This can be resolved for an individual document by using `\setmainfont[RawFeature=-normalize]{Old Standard}`.
> 
> The problem is that new luaotfoad versions normalize to NFC before shaping and Unicode considers the composed characters with tonos and with oxia to be the same, therefore they get normalized to the same glyph. I'm not sure what to do about that.

This is very unfortunate because it introduces confusion.  Strictly speaking, tonos and vowels + tonos are not to be confused with their “acute” counterparts.  Furthermore, they do not refer to the same Unicode code points.  Could you please have a look at the current documentation of OldStandard on CTAN on pp. 5-6 about this (about `ss06`)?  (http://mirrors.ctan.org/fonts/oldstandard/doc/oldstandard.pdf)

In my opinion, retaining the distinction betweed tonos and oxia would not harm, because most—if not all—fonts do not make the distinction and so would print Greek just as expected.  But it would allow those few for whom the distinction matters to use adequate fonts and have tonos or oxia printed distinctly.

I wonder why Harfbuzz behaves differently, namely “the right way” if I may say so?

> Some options:
> 
>   * Disable normalization by default when `script=grek` is set. But this can reintroduce other issues and preserves the distinct rendering of equivalent input, leading e.g. to issues like https://tex.stackexchange.com/q/542789/80496 when the editor doesn't play the same game.
>   * Automatically add the equivalent of https://tex.stackexchange.com/q/542789/80496 whenever the language is set to polytonic greek. This solves the issue with Oxia/Tonos as long as the language is set correctly independent from the input, but it doesn't work if the language isn't set (which might happen due to fontspec removing it to an an unsupported language)

Thank you for pointing these out.  As a matter of fact, I am preparing a new package in collaboration with a friend to deal with just issues as this one.

I use emacs which provides very accurate keyboards for every usage...

>   * Consider this a font bug since canonically equivalent characters should look the same. We would have a point, but declaring it someone else's problem is not exactly the most productive solution...

Well, I would argue it is not a bug, rather a feature that I am preparing to be included in OldStandard... ;)

Thank you again!

Robert

> @jbezos Any opinion on this?

**Comment by zauguin** [comment]
> Furthermore, they do not refer to the same Unicode code points.

They do not refer to *the same* Unicode codepoints, but they refer to *canonically equivalent* Unicode codepoints. Therefore they normalize to the same codepoints.

> In my opinion, retaining the distinction betweed tonos and oxia would not harm, because most—if not all—fonts do not make the distinction and so would print Greek just as expected.

That could be seen as an argument for either solution.

Anyway the harm isn't so much in greek, it's in the general principle of not normalizing the text. There is a reason why we added that, especially since many fonts (especially ones quite common in TeX) do not support decomposed characters properly and therefore break pretty bad for non normalized text.
Also more generally, making a distinction between canonically equivalent glyph sequences breaks quite some assumptions in Unicode workflows and IMO will just lead to more trouble than it's worth.

> Could you please have a look at the current documentation of OldStandard on CTAN on pp. 5-6 about this (about `ss06`)?

> However, strictly speaking, tonos is not to be mistaken for ‘acute’: that is for
> sure, as tonos was introduced as a result of a reform to denote a tone, [...].
>
> Since assigning vowels with tonos and vowels with acute to the same code
> points is clearly unacceptable even if the glyphs are identical, 

By Unicode policy "Diacritic marks are not encoded by function, and are not specific to language or usage." (quoted from the FAQ on combining character, but the standard says something similar IIRC)
The standard makes it pretty clear that the difference between tonos and oxia is considered a difference in rendering the acute accent in monotonic or polytonic greek and therefore not a difference represented in Unicode.

> I wonder why Harfbuzz behaves differently, namely “the right way” if I may say so?

HarfBuzz intents to shape canonically equivalent sequences the same, but as a performance optimization it doesn't touch single character clusters when normalizing to composed forms (https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-ot-shape-normalize.cc#L54). Since this is a side effect of an optimiztion is is rather fragile, e.g. if you would try to add an additional combining character to the construct then it would use the tonos too.

> Well, I would argue it is not a bug, rather a feature that I am preparing to be included in OldStandard.

Please don't. Using canonically equivalent sequences to mean different things just leads to pain. It is hard to input (keyboard layouts are one thing, but many editors also automatically normalize, sometimes while writing and sometimes while saving. (E.g. I've seen someone using a font doing something like this who was very surprised when editing a completely unrelated part of the document with another editor changed characters all over the place since the editor normalized the text before saving...)

Is there any reason why this can't be controlled by the language? Given that I don't speak or write Greek I might be completely wrong here, but I understood it in the way that tonos is only used in monotonic and oxia only in polytonic greek. Then the font could just substitute the oxia glyph if the language is set to polytonic greek.
