### ISSUE TITLE
How to enable kerning in math mode?

### ISSUE THREAD

**Issue by Weisser-Kater** [latex3/luaotfload#223]
I have beought the Minion Math font from Typoma:
http://www.typoma.com/en/fonts.html

As we can read on this website the fonts contain kerning information in the mathematical alphabet.

> Since Release 1.020, each font style already contained approximately 2.900 glyphs, with a real Math Italic alphabet (wider than Text Italic, and with special kerning).

So how can I get the kerning in math mode? When setting `script=math` all kerning is deleted.

**Comment by zauguin** [comment]
There are multiple aspects here:

  1. LuaTeX mostly doesn't apply regular kerning in math mode. We could probably change that to some degree, but that would need a good usecase and an available test font which uses that functionality. 
  2. Given that in your case setting `script=math` disabled kerning it seems that the font doesn't even specify kerning when loaded as a math font but only when used as a text font. (Which seems like correct behavior based on the OpenType math spec which doesn't suggest kerning for math fonts.) In that case it's by design.
