### ISSUE TITLE
dviluatex: Unable to register callback

### ISSUE THREAD

**Issue by schlcht** [latex3/luaotfload#240]
(Filing this on the minute chance that I'm not missing something obvious...)

The following, fed to dviluatex, results in a `luatexbase Error: Unable to register callback.` All is fine with plain (not dvi) luatex.

```
\input luaotfload.sty
\font\x=lmroman10-regular
\bye
```

**Comment by zauguin** [comment]
This is more or less by design. In order to allow useful DVI output luaotfload has to rewrite the used glyphs before they are shipped in the output. The most reliable way to do that is to do this directly before shipout. Since LuaTeX doesn't provide a callback there this needs help from the output routine. In LaTeX this is implemented, in plain the user is responsible for adjusting the output routine if they want to use DVI mode.
