### ISSUE TITLE
Why LuaLaTeX adds rot13 feature into any OpenType?

### ISSUE THREAD

**Issue by AlphaJack** [latex3/luaotfload#257]
From https://tex.stackexchange.com/q/666181/213962

"There's obviously no practical use for this; I'm guessing that it's there to help with testing the feature code."

https://github.com/latex3/luaotfload/blob/main/src/luaotfload-features.lua#L617-L638

**Comment by zauguin** [comment]
Not a bug

**Comment by u-fischer** [comment]
We don't know why the feature is there. The source code is imported from context but doesn't contain any comment about the purpose of the feature. I suggest that you ask on the context mailing list (https://wiki.contextgarden.net/Mailing_Lists). Perhaps there someone remembers why it was added.

**Comment by zauguin** [comment]
The `rot13` feature is not part of the imported code but luaotfload specific. It was added in https://github.com/latex3/luaotfload/commit/a55edde26344366c385e433824d3e78fec618158 to demonstrate custom font features doing single char replacements.

**Comment by u-fischer** [comment]
> The `rot13` feature is not part of the imported code but luaotfload specific. It was added in [a55edde](https://github.com/latex3/luaotfload/commit/a55edde26344366c385e433824d3e78fec618158) to demonstrate custom font features doing single char replacements.

Oh, I thought it was already in the context files. Then we should really document it imho.

**Comment by zauguin** [comment]
Not sure how this best fits into the documentation. We could document what it does, but that wouldn't really help anyone since it's rather useless. AFAICT it was added to play around with substitution and then stayed in since there's basically no cost in having it there and it seems like a funny easteregg.

Maybe we should add the implementation as an example how to add a new substitution feature and then mention that it is already predefined? Or remove it from the code and only add it in the documentation as an example?

**Comment by zauguin** [comment]
Added in be130bb5.
