### ISSUE TITLE
improving generation of large fonts

### ISSUE THREAD

**Issue by u-fischer** [latex3/luaotfload#49]
Some fonts (CJK fonts mostly) are so large that the generation of the lua file takes quite long or even fails eating up the memory (I had to use 64bit luatex for some of them).

Is the code suggested in https://tex.stackexchange.com/a/479753/2388 a possible option and  can there be some interface for it?

~~~~
fonts.handlers.otf.readers.registerextender {
    name   = "remove names from Noto Sans CJK SC",
    action = function(fontdata)
        if string.match(fontdata.metadata.fullname, "Noto Sans CJK SC") then
            texio.write_nl("Trimming font " .. fontdata.metadata.fullname)
            for k, v in next, fontdata.descriptions do
                v.name = nil
            end
        end
    end
}
~~~~

**Comment by Firestar-Reimu** [comment]
I am thinking of rewriting luaotfload in C and only use lua to make interfaces

**Comment by zauguin** [comment]
I'm not sure what you are saying. This issue is about some versions having very slow cache generation for huge fonts while your experiments are all running with preexisting caches. Therefore it would be very surprising if adding that codeblock would make any difference.

Beside that @u-fischer I'm relatively sure that these names are stripped anyway. Could you test whether adding this block still makes any difference to generation times on Windows?

**Comment by u-fischer** [comment]
@zauguin  No there is no time difference. The cjk fonts works fine now, also without a 64bit luatex. One could simply close this here imho.

**Comment by Firestar-Reimu** [comment]
So the current problem is that it is slow **after** generating font caches? [This test](https://stone-zeng.github.io/2019-07-24-tex-benchmark/) also found this.

**Comment by zauguin** [comment]
@Firestar-Reimu If current versions are very slow for some fonts please open an issue for that, but in my experiments the loading time seems reasonable. (My system currently uses 0.07s to load Noto Sans CJK SC, half of which is the time needed by LuaTeX itself to parse the font table we send from Lua)

**Comment by Firestar-Reimu** [comment]
@zauguin See #279 , thanks
