### ISSUE TITLE
Characters with Default_Ignorable_Code_Point property should invisible by default

### ISSUE THREAD

**Issue by khaledhosny** [latex3/luaotfload#63]
Default Ignorable characters are control characters that should be invisible by default even if the font has glyphs for them. This is not exactly spec’d (in the context of OpenType) anywhere AFAIK, butt see The Unicode Standard, page 250, [***Characters Ignored for Display***](https://www.unicode.org/versions/Unicode12.0.0/ch05.pdf#G40095) for general Unicode guidelines on this.

AFAIK, major OpenType layout engines (HarfBuzz, Uniscribe, Core Text, etc.) all implement this in some degree, and some provide an option to render these characters with glyphs provided by the font (useful for debugging). The exact list of characters that should behave like this can be found in [HarfBuzz sources](https://github.com/harfbuzz/harfbuzz/blob/7dcfc5357df879491f847bd7d2941645e58f268c/src/hb-unicode.hh#L134-L170).

This test file should give unligated f and i glyphs, but with luaotfload it shows a vertical line between the two glyphs:
```tex
\input ifluatex.sty
\ifluatex\input luaotfload.sty\fi
\font\amiri="[amiri-regular.ttf]" at 200pt
\amiri f\char"200C i
\bye
```

**Comment by u-fischer** [comment]
Related https://github.com/lualatex/luaotfload/issues/317
https://github.com/alif-type/amiri/issues/160

One can suppress it along the patch in the second link:

~~~~
\documentclass{article}
\usepackage{fontspec}
\usepackage{luacode}

\begin{luacode}

local patch_amiri = function (fontdata)
 if fontdata.fontname == "Amiri-Regular"
 then
   fontdata.characters[8204]["index"]=3
   fontdata.characters[8205]["index"]=3
 end
end

luatexbase.add_to_callback
 (
  "luaotfload.patch_font",
   patch_amiri,
  "change_amiri"
 )
\end{luacode}

\setmainfont[Script=Arabic]{Amiri}

\begin{document}

f\char"200C i
\end{document}
~~~~

So it is possible to make them invisible. The main question is how to do it at best.

**Comment by u-fischer** [comment]
Side remark: with mode=harf the glyph is shown too.

**Comment by khaledhosny** [comment]
The fix shouldn’t be font specific, so if patching callback is to be used then it should be applied to all fonts (simply checking if the font has the character and patch it).

> Side remark: with mode=harf the glyph is shown too.

Not here:
```tex
\input ifluatex.sty
\ifluatex\input harfload.sty\fi
\font\amiri="[amiri-regular.ttf]:mode=harf" at 200pt
\amiri f\char"200C i
\bye
```
(with or without `mode=harf` I get the following output, when `harfload` is used it will default to `harf` mode if no mode is set).
![image](https://user-images.githubusercontent.com/93914/59165107-d1635480-8b16-11e9-9572-109efdb4a5bb.png)

**Comment by khaledhosny** [comment]
Also fonts might not set the glyph width of these characters to zero, so that must be ensured as well.

**Comment by u-fischer** [comment]
Sorry, you are right, it works with harf (I had forgotten to load harfload, it would probably good to integrate it directly into the format if possible).

**Comment by zauguin** [comment]
> Default Ignorable characters are control characters that should be invisible by default even if the font has glyphs for them. This is not exactly spec’d (in the context of OpenType) anywhere AFAIK, butt see The Unicode Standard, page 250, Characters Ignored for Display for general Unicode guidelines on this.

I read the Unicode Standard differently: About characters with property "Default_Ignorable_Code_Point" it says:

> **Default Ignorable Code Point**. The list of characters which should be ignored for display in  fallback  rendering  is  given  by  a  character  property:  Default_Ignorable_Code_Point(DI).

So according to this, DI only says that they should be ignored in *fallback rendering*, which is defined by

> **Fallback Rendering**. Fallback  rendering  occurs  when  a  text  process  needs  to  display  a character or sequence of characters, but lacks the rendering resources to display that character correctly.

This doesn't really apply here, because we render the glyph with a glyph from the current font, so we do not "lack the rendering resources to display that character correctly". Therefore we are in "Normal Rendering". Then, the standard says:

> **Normal Rendering**. Many characters, including format characters and variation selectors, have no visible glyph or advance width directly associated with them. Such characters without glyphs are typically shown in the code charts [...] Outside of the particular context of code chart display, a font will typically display no glyph for such characters.

In my opinion this explicitly states that a font typically shouldn't provide glyphs for such characters, but if a glyph *is* provided by a font, from our perspective the condition "have no visible glyph or advance width directly associated with them" is no longer met. So I do not see any rule in the specification which would allow us to ignore these characters.

**Comment by khaledhosny** [comment]
> Outside of the particular context of code chart display, a font will **typically** display no glyph for such characters.

That is a descriptive not a normative condition.

Regardless of how one reads this, the behavior I describes is implemented by all major text layout engines (Unriscribe/DirectWrite, HarfBuzz, Core Text, various Adobe text layout engines). Many common fonts have visible glyphs for some Default_Ignorable characters, it is even a Microsoft recommendation for some of them. Luaotfload/context is the odd one here.

**Comment by khaledhosny** [comment]
BTW, fallback rendering here means that the rendering does not support handling the special effect these characters cause (e.g. ZWNJ preventing ligatures), not fallback rendering for missing glyphs.

**Comment by zauguin** [comment]
> That is a descriptive not a normative condition.

That's why I didn't say that this is a font bug or similar, but even then I do not see the rule for hiding these glyphs.

My point is that if we implement this, we should implement the actual rule and not some approximation based on some fallback property.

> BTW, fallback rendering here means that the renderer does not support handling the special effect these characters cause (e.g. ZWNJ preventing ligatures), not fallback rendering for missing glyphs.

@khaledhosny What are you basing this on? In the linked version of the standard missing glyphs are the canonical example for fallback rendering.
For "formatting characters", their formatting effect has to be supported too, but this effect is not specified by DI. Especially, if we rely in DI, we would treat these characters as not supported and should therefore "ignore them for display", which I do not think is the behaviour you want. E.g. I do not think that you want ZWNJ to be ignored in ligature building.

So while some characters should be ignored, I do not see why "Default_Ignorable_Code_Point" would be the best condition.

**Comment by khaledhosny** [comment]
I provided a link to HarfBuzz sources with the actual list of code points it hides, you can use that. Otherwise there is no definitive specification here. The Unicode core spec text about Default_Ignorables is the closest you can get.

**Comment by u-fischer** [comment]
I think we all agree that the glyphs should (normally) not be shown.  So the main question is what to do about it. For luaotfload alone I would say, that it is simply one of the various examples of problems the fontloader has with such scripts and close with "will work with harf mode". 

But there is the additional problem of `arabluatex`: imho it is affected by the problem too and I don't know if it will be able to use harf mode. If not they should perhaps be an option/a feature to ignore this glyphs when using mode=node. I guess I will have to ask Robert about a comment.

**Comment by khaledhosny** [comment]
I’m fine with closing. `arabluatex` should work with `mode=harf`.

**Comment by zauguin** [comment]
> For luaotfload alone I would say, that it is simply one of the various examples of problems the fontloader has with such scripts and close with "will work with harf mode".

I disagree, mostly because it is not that hard to implement, so once we know which characters should be affected I see no reason not to add a feature for this.

I think the current options are for the affected characters are:

- Whatever HarfBuzz is doing
- Unicode's Default_Ignorable_Code_Point

Here "Whatever HarfBuzz is doing" is a subset of "Default_Ignorable_Code_Point" with exceptions for Hangul fillers and [shorthand formatting glyphs](https://github.com/harfbuzz/harfbuzz/issues/503).

Looking a bit into this I found a quite interesting discussion on the Unicode mailing list about this from 2002 when Default_Ignorable_Code_Point was added. The question was if Unicode should add a property "Invisible" in addition to "Default_Ignorable_Code_Point". Back then, AFAICT the UTC decided to modify Default_Ignorable_Code_Point to define exactly these characters.

This is sufficiently confirmation for me that Default_Ignorable_Code_Point is the right property here, so the interesting question are HarfBuzz's exceptions. The Hangul fillers have been added to Default_Ignorable_Code_Point precisly as a result of the discussion mentioned above, so I think it is at least curious that it is handled differently by HarfBuzz. Can someone test how these behave on Apple systems? (Apple initiated the "Invisible" discussion back then, so it would be interesting what they are doing now.)

For the shorthand glyphs I am a bit confused why they are even excluded by HarfBuzz because the issue linked above sounded as if they wanted to delegate the discussion to the Unicode team and I couldn't find any response from them.

**Comment by u-fischer** [comment]
@zauguin if you think it can be implemented go along. Perhaps with some options to configure it. 

As a rule of thumb I would go along "what harfbuzz is doing" unless some strong argument is against it, assuming that due to the large user base they probably found a sensible way to handle the unclear points. 

I learned enough from Barbara and David to not expect unicode to be logical everywhere ... and you could ask them if they have some idea how to clarify some points.

[https://xkcd.com/1726/](url)

**Comment by zauguin** [comment]
@khaledhosny @u-fischer I added an initial implementation in the [ignorable](https://github.com/latex3/luaotfload/tree/ignorable) branch. Could you test it? It currently requires to manually place a copy of [PropList.txt](https://www.unicode.org/Public/12.1.0/ucd/PropList.txt) where TeX can find it. (I will propose that one for unicode-data later.)

**Comment by u-fischer** [comment]
@zauguin  
I'm not sure that I understand the conditions the glyphs should not be shown, but this example still
shows them:

```
\documentclass{article}
\begin{document}
\font\amiri="[amiri-regular.ttf]" at 20pt
\amiri 
\char"200Dي\char"200D

ي\char"200D

\char"200Dي

ي

\end{document}
```

![image](https://user-images.githubusercontent.com/4047173/63214846-eadbda80-c11d-11e9-94c2-59396f04142a.png)

**Comment by zauguin** [comment]
@u-fischer Should be fixed now, the earlier version didn't make the feature the default, so it required `:+invisible`. Now `invisible` is the default but can be explicitly disabled.

**Comment by u-fischer** [comment]
Works fine. I will add some documentation so that we keep track of the changes.

**Comment by u-fischer** [comment]
Works in dev/bidi-dev.
