### ISSUE TITLE
utf8 module breaks compatibility with LuajitTeX

### ISSUE THREAD

**Issue by e-kwsm** [latex3/luaotfload#89]
9e5ac3b90c297374d0272884914347097c516d9c introduces `utf8`, new in Lua 5.3, but LuajitTeX does not support it yet.

The latest luatex (version 1.10.0) is compiled with Lua 5.3.5, while luajittex (1.10.0) with LuaJIT 2.1.0-beta3 (`_VERSION` is `Lua 5.1`).

Consequently, luajittex does not work:
```shellsession
$ luajittex --fmt=luajitlatex.fmt '\documentclass{article}'
This is LuajitTeX, Version 1.10.0 (TeX Live 2019) 
 restricted system commands enabled.
LaTeX2e <2018-12-01>


luaotfload | load : FATAL ERROR
luaotfload | load :   × Failed to load module "luaotfload-database.lua".
luaotfload | load :   × Error message:
luaotfload | load :     × "...texmf-dist/tex/luatex/luaotfload/luaotfload-database.lua:174: attempt to index global 'utf8' (a nil value)".

stack traceback:
	...019/texmf-dist/tex/luatex/luaotfload/luaotfload-main.lua:171: in function 'loadmodule'
	...019/texmf-dist/tex/luatex/luaotfload/luaotfload-main.lua:237: in function 'initialize'
	...019/texmf-dist/tex/luatex/luaotfload/luaotfload-main.lua:289: in function 'main'
	[\directlua]:1: in main chunk

```

The version of luaotfload is 2.99.

Is it possible to check if `utf8` is available?

**Comment by josephwright** [comment]
I'm not sure that LuaJITTeX has a future: if it's not being updated for LuaTeX changes, that's a killer.

**Comment by e-kwsm** [comment]
LuaJIT does not support `utf8` (LuaJIT/LuaJIT#270).

**Comment by josephwright** [comment]
I should add that I'm not saying a test can't be used: we have something similar in `l3build` to cover different LuaTeX releases.

**Comment by u-fischer** [comment]
I suggest that you use the texlive backup for now to revert to version 2.98 and then don't update luaotfload/lualibs unless we are explicitly saying that it works with luajittex too.

**Comment by e-kwsm** [comment]
The correspondence table is as follows:

| `utf8` | `unicode.utf8` |
|--|--|
| `utf8.char` | `unicode.utf8.char` |
| `utf8.codepoint` | `unicode.utf8.byte` |
| `utf8.codes` | na |
| `utf8.len` | `unicode.utf8.len` |
| `utf8.offset` | `unicode.utf8.offset` |

I copied `utf8_codes` (and `utf8_decode`) from [this patch](https://github.com/LuaJIT/LuaJIT/pull/270/files), then luaotfload seems to work with LuajitTeX, but probably such a situation is undesirable.

If luaotfload has no intention to support LuajitTeX, then luaotfload should raise comprehensible error message rather than Lua's low level one.

**Comment by u-fischer** [comment]
No we don't have the intention to support LuajitTeX. We don't have the time and man power to test and maintain luaotfload and latex against a variety of luatex engines, luatex versions and lua versions. So we target one engine and also only a rather small version range (a current luaotfload doesn't work in older texlive). 

This isn't really new: luaotfload never tested if it works with luajittex. It worked because the engines were similar enough.  I will adjust the readme and documentation to make this point clearer.

You could try to setup the needed libraries in the ini-file of the  format before luaotfload-main is loaded.  E.g. if I do this in plain luajittex luaotfload loads (but fails in the font definition):

~~~~
\directlua{require("lualibs")}
\directlua{print(table.serialize(unicode))} % to look
\directlua{utf8= unicode.utf8 or {} 
           utf8.codepoint = unicode.utf8.byte
          }
\input luaotfload.sty
abc
\font\test={Arial}\test abc

\bye
~~~~

But imho even if it works it would be still rather fragile due to the old lua version. A better solution would be to ask the luajittex maintainer to update the binary so that it stays more in sync with luatex.

**Comment by khaledhosny** [comment]
LuaJIT does not seem to have any plans for upgrading Lua API support https://github.com/LuaJIT/LuaJIT/issues/198

**Comment by e-kwsm** [comment]
JFYI: [MoonJIT](https://github.com/moonjit/moonjit) and [RaptorJIT](https://github.com/raptorjit/raptorjit) are forks of LuaJIT and backporting `utf8` (moonjit/moonjit#38, raptorjit/raptorjit#259).
